/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
